name: Go CI / CD 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build cmd/jsonparser/jsonparser.go
    
    - name: Test
      run: go test 

  build-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build cmd/jsonparser/jsonparser.go

    - name: Test
      run: go test 